import "./globals.css";

export const metadata = {
  title: "Safdar Ali Shah",
  description: "Generated by NexT Engine",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
